### ISSUE TITLE
编译H5出错

### ISSUE THREAD

**Issue by gdunser** [NervJS/taro-todo#1]
./.temp/components/foot/foot.js
Module not found: Can't resolve '@tarojs/components' in '/Users/rain/Documents/source/taro/todo/.temp/components/foot'

**Comment by gdunser** [comment]
weapp是没问题的

**Comment by 1271651135** [comment]
同问

**Comment by mrarronz** [comment]
按照说明安装依赖，使用命令taro build --type h5 --watch时出现以下错误：

UnhandledPromiseRejectionWarning: Error: Cannot find module './Mime'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/arronzhu/Desktop/taro-todo-master/node_modules/mime/index.js:3:12)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
(node:11322) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11322) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by giantss** [comment]
@luckyadam @mrarronz  我遇到同样的问题。解决吗？

**Comment by Vidtion** [comment]
我也碰到了，我开始用yarn创建的项目，中途用npm装了一个包，然后运行就报错，最后`npm i`重新安装下依赖，就好了。
